### ISSUE TITLE
Integration with puppeteer-extra 

### ISSUE THREAD

**Issue by paularah** [microlinkhq/browserless#225]
Using puppeteer-extra gives me this error. This seems to be the case only when trying to use browserless  with puppeteer-extra 

UhandledPromiseRejectionWarning: Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

**Comment by Kikobeats** [comment]
Hey, that error message looks a thing related to the Firefox build rather than puppeteer-extra

BTW, `puppeteer-firefox` should be supported
https://github.com/microlinkhq/browserless/blob/0f91811aceea3f98ee5515f97c33c0ee503756b7/packages/browserless/src/index.js#L17

Can you try with `puppeteer-core`? what happens in that case?

**Comment by edembasket** [comment]
@paularah, did you find a solution to the error above?

**Comment by edemagbenyo** [comment]
@paularah , did you find a solution to the error above?

**Comment by paularah** [comment]
@edemagbenyo I did.  


`//do all the puppeteer extra stuff above, use your plugins and then use your instance of puppeteer-extra with browserless like this.
 await browserless.html(, {
            puppeteer:puppeteer-extra,
        })
`
This workaround works for me and is stable.
`
// N/B: Integrating puppeteer-extra and browserless like this as specified in the docs doesn't work for me
const browserless = require('browserless')({ puppeteer }) 

`
