### ISSUE TITLE
Failed with vercel deployments or pkg bundling

### ISSUE THREAD

**Issue by huozhi** [microlinkhq/browserless#260]
### Prerequisites

- [x] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Failed to deploy apps relying on browserless to vercel

browserless is using prism-themes as dependency, but prism-themes doesn't have a valid main entry (should be a valid js file path). It caused deployment failures on vercel. I also tried with vercel/pkg, it failed as well.

### Steps to reproduce

I'm deploying [next-imagegen-example](https://github.com/huozhi/next-imagegen-example) to vercel with puppeteer provider (which is using browserless)

you can use `vercel/pkg` to bundle [imagegen-puppeteer-provider](https://github.com/huozhi/next-plugin-imagegen/tree/master/packages/next-plugin-imagegen-puppeteer) as well

### Expected behaviour

Deployment should work well

### Actual behaviour

Deployment failed with error that they couldn't resolve module prism-themes

### Ideal Workaround

change `require.resolve` for prism-themes to sth else. maybe `path.resolve`

**Comment by Kikobeats** [comment]
I'm not sure why `vercel/pkg` is failing, but `require.resolve` is a standard Node.js API that should be works.

In this case, it is necessary to find where is `prism-themes` living:

<img width="839" alt="Screen Shot 2021-03-13 at 20 45 25" src="https://user-images.githubusercontent.com/2096101/111042302-0bc0fa80-843d-11eb-83e5-bf00addcf242.png">

Since the `main` file declared at `package.json` at `prism-themes` is a markdown file, it's necessary to navigate to point the folder of themes (that's probably the thing that can be improved doing a PR there)

Anyway, I think you don't need to require the path at all, so the thing I did as a temporal workaround is to lazily require the prism theme on demand.
